### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by dimitrisnl**
---- Autogenerated Waffleboard Connection: Connects to #33
---- Autogenerated Waffleboard Connection: Connects to #50
---- Autogenerated Waffleboard Connection: Connects to #25

### CODE REVIEW

**Comment by dimitrisnl** [comment]
@mikesimos Should I include a ISC licence?

**Comment by mikesimos** [comment]
@dimitrisnl yes, looks like we need a licence. Not sure if we need to restore [this](https://github.com/resin-io/resin-blog/commit/be716032e501a9135f809c5297207b52910c98be)

**Comment by dimitrisnl** [comment]
@mikesimos Can we do something about these node errors? It's surprising that node4 fails too.

**Comment by brownjohnf** [comment]
Sorry about the confusion here. The various node failures should just be ignored; ResinCI is still in experimental mode. The license check was in error; the valid conditions are no license file, an apache 2.0 license, or AGPL. So really this should probably be apache 2.0, but it's worth confirming.

**Comment by dimitrisnl** [comment]
Can't use npm ci due to the node version.

jQuery is being used, but referenced in the dashboard, in the footer script
textarea

**Pull request merged**
